/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ControladorReportes;

/**
 *
 * @author PC
 */
public class Reportes extends javax.swing.JPanel {

    /**
     * Creates new form Reportes
     */
    ControladorReportes controlador;
    public Reportes() {
        initComponents();
        controlador = new ControladorReportes(this);
    }

    // Getters para los botones de búsqueda
    public javax.swing.JButton getBtnBuscarReportesClientes() {
        return btnBuscarReportesClientes;
    }

    public javax.swing.JButton getBtnBuscarRepoBoletas() {
        return btnBuscarRepoBoletas;
    }

    public javax.swing.JButton getBtnBuscarPedidos() {
        return btnBuscarPedidos;
    }

    public javax.swing.JButton getBtnBuscarIDPedidosComandas() {
        return btnBuscarIDPedidosComandas;
    }

    public javax.swing.JButton getBtnBuscarRegEntregas() {
        return btnBuscarRegEntregas;
    }

    public javax.swing.JButton getBtnBuscarGuiaRem() {
        return btnBuscarGuiaRem;
    }

// Getters para los botones de exportar
    public javax.swing.JButton getBtnExportarRepoClientes() {
        return btnExportarRepoClientes;
    }

    public javax.swing.JButton getBtnExportarRepoBoletas() {
        return btnExportarRepoBoletas;
    }

    public javax.swing.JButton getBtnExportarRepoPedidos() {
        return btnExportarRepoPedidos;
    }

    public javax.swing.JButton getBtnExportarReportesComandas() {
        return btnExportarReportesComandas;
    }

    public javax.swing.JButton getBtnExportarRepoRegEntregas() {
        return btnExportarRepoRegEntregas;
    }

    public javax.swing.JButton getBtnExportarRepoGuiaRem() {
        return btnExportarRepoGuiaRem;
    }

// Getters para los botones de imprimir
    public javax.swing.JButton getBtnRepoImprimir() {
        return btnRepoImprimir;
    }

    public javax.swing.JButton getBtnImprimirReporteBoletas() {
        return btnImprimirReporteBoletas;
    }

    public javax.swing.JButton getBtnImprimirRepoPedidos() {
        return btnImprimirRepoPedidos;
    }

    public javax.swing.JButton getBtnImprimirRepoComandas() {
        return btnImprimirRepoComandas;
    }

    public javax.swing.JButton getBtnImprimirRepoRegEntregas() {
        return btnImprimirRepoRegEntregas;
    }

    public javax.swing.JButton getBtnImprimirGuiaRem() {
        return btnImprimirGuiaRem;
    }

// Getters para las tablas
    public javax.swing.JTable getTablaReporteClientes() {
        return tablaReporteClientes;
    }

    public javax.swing.JTable getTablaReportesBoletas() {
        return tablaReportesBoletas;
    }

    public javax.swing.JTable getTablaRepoPedidos() {
        return tablaRepoPedidos;
    }

    public javax.swing.JTable getTablaReporteComandas() {
        return tablaReporteComandas;
    }

    public javax.swing.JTable getTablaRepoRegEntregas() {
        return tablaRepoRegEntregas;
    }

    public javax.swing.JTable getTablaReporteGuiaRem() {
        return tablaReporteGuiaRem;
    }

// Getters para los campos de texto de búsqueda
    public javax.swing.JTextField getTxtClientesID() {
        return txtClientesID;
    }

    public javax.swing.JTextField getTxtIDBoletaBusqueda() {
        return txtIDBoletaBusqueda;
    }

    public javax.swing.JTextField getTxtIDPedidos() {
        return txtIDPedidos;
    }

    public javax.swing.JTextField getTxtIDPedidoComandas() {
        return txtIDPedidoComandas;
    }

    public javax.swing.JTextField getTxtIDRegEntregas() {
        return txtIDRegEntregas;
    }

    public javax.swing.JTextField getTxtIDPedidosGuiaRem() {
        return txtIDPedidosGuiaRem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelBoletas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtIDBoletaBusqueda = new javax.swing.JTextField();
        btnBuscarRepoBoletas = new javax.swing.JButton();
        btnExportarRepoBoletas = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaReportesBoletas = new javax.swing.JTable();
        btnImprimirReporteBoletas = new javax.swing.JButton();
        jPanelClientes = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaReporteClientes = new javax.swing.JTable();
        btnRepoImprimir = new javax.swing.JButton();
        btnExportarRepoClientes = new javax.swing.JButton();
        btnBuscarReportesClientes = new javax.swing.JButton();
        txtClientesID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanelComandas = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaReporteComandas = new javax.swing.JTable();
        btnImprimirRepoComandas = new javax.swing.JButton();
        btnExportarReportesComandas = new javax.swing.JButton();
        btnBuscarIDPedidosComandas = new javax.swing.JButton();
        txtIDPedidoComandas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanelGuiaRem = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaReporteGuiaRem = new javax.swing.JTable();
        btnImprimirGuiaRem = new javax.swing.JButton();
        btnExportarRepoGuiaRem = new javax.swing.JButton();
        btnBuscarGuiaRem = new javax.swing.JButton();
        txtIDPedidosGuiaRem = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanelPedidos = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaRepoPedidos = new javax.swing.JTable();
        btnImprimirRepoPedidos = new javax.swing.JButton();
        btnExportarRepoPedidos = new javax.swing.JButton();
        btnBuscarPedidos = new javax.swing.JButton();
        txtIDPedidos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanelRegEntregas = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablaRepoRegEntregas = new javax.swing.JTable();
        btnImprimirRepoRegEntregas = new javax.swing.JButton();
        btnExportarRepoRegEntregas = new javax.swing.JButton();
        btnBuscarRegEntregas = new javax.swing.JButton();
        txtIDRegEntregas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        jPanelBoletas.setPreferredSize(new java.awt.Dimension(806, 482));

        jLabel3.setText("ID (Boleta): ");

        btnBuscarRepoBoletas.setText("Buscar");

        btnExportarRepoBoletas.setText("Exportar");

        tablaReportesBoletas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaReportesBoletas);

        btnImprimirReporteBoletas.setText("Imprimir");

        javax.swing.GroupLayout jPanelBoletasLayout = new javax.swing.GroupLayout(jPanelBoletas);
        jPanelBoletas.setLayout(jPanelBoletasLayout);
        jPanelBoletasLayout.setHorizontalGroup(
            jPanelBoletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBoletasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBoletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBoletasLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDBoletaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarRepoBoletas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExportarRepoBoletas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImprimirReporteBoletas)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelBoletasLayout.setVerticalGroup(
            jPanelBoletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBoletasLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanelBoletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIDBoletaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarRepoBoletas)
                    .addComponent(btnExportarRepoBoletas)
                    .addComponent(btnImprimirReporteBoletas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Boletas", jPanelBoletas);

        tablaReporteClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaReporteClientes);

        btnRepoImprimir.setText("Imprimir");

        btnExportarRepoClientes.setText("Exportar");

        btnBuscarReportesClientes.setText("Buscar");

        jLabel4.setText("ID (Clientes): ");

        javax.swing.GroupLayout jPanelClientesLayout = new javax.swing.GroupLayout(jPanelClientes);
        jPanelClientes.setLayout(jPanelClientesLayout);
        jPanelClientesLayout.setHorizontalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClientesLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClientesID, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarReportesClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExportarRepoClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRepoImprimir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelClientesLayout.setVerticalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientesLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtClientesID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarReportesClientes)
                    .addComponent(btnExportarRepoClientes)
                    .addComponent(btnRepoImprimir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clientes", jPanelClientes);

        tablaReporteComandas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tablaReporteComandas);

        btnImprimirRepoComandas.setText("Imprimir");

        btnExportarReportesComandas.setText("Exportar");

        btnBuscarIDPedidosComandas.setText("Buscar");

        jLabel5.setText("ID (Pedidos): ");

        javax.swing.GroupLayout jPanelComandasLayout = new javax.swing.GroupLayout(jPanelComandas);
        jPanelComandas.setLayout(jPanelComandasLayout);
        jPanelComandasLayout.setHorizontalGroup(
            jPanelComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComandasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelComandasLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDPedidoComandas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarIDPedidosComandas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExportarReportesComandas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImprimirRepoComandas)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelComandasLayout.setVerticalGroup(
            jPanelComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComandasLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanelComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtIDPedidoComandas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarIDPedidosComandas)
                    .addComponent(btnExportarReportesComandas)
                    .addComponent(btnImprimirRepoComandas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Comandas", jPanelComandas);

        tablaReporteGuiaRem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tablaReporteGuiaRem);

        btnImprimirGuiaRem.setText("Imprimir");

        btnExportarRepoGuiaRem.setText("Exportar");

        btnBuscarGuiaRem.setText("Buscar");

        jLabel6.setText("ID (Pedidos): ");

        javax.swing.GroupLayout jPanelGuiaRemLayout = new javax.swing.GroupLayout(jPanelGuiaRem);
        jPanelGuiaRem.setLayout(jPanelGuiaRemLayout);
        jPanelGuiaRemLayout.setHorizontalGroup(
            jPanelGuiaRemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGuiaRemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGuiaRemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGuiaRemLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDPedidosGuiaRem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarGuiaRem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExportarRepoGuiaRem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImprimirGuiaRem)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelGuiaRemLayout.setVerticalGroup(
            jPanelGuiaRemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGuiaRemLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanelGuiaRemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtIDPedidosGuiaRem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarGuiaRem)
                    .addComponent(btnExportarRepoGuiaRem)
                    .addComponent(btnImprimirGuiaRem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Guias Rem.", jPanelGuiaRem);

        tablaRepoPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tablaRepoPedidos);

        btnImprimirRepoPedidos.setText("Imprimir");

        btnExportarRepoPedidos.setText("Exportar");

        btnBuscarPedidos.setText("Buscar");

        jLabel7.setText("ID (Pedidos): ");

        javax.swing.GroupLayout jPanelPedidosLayout = new javax.swing.GroupLayout(jPanelPedidos);
        jPanelPedidos.setLayout(jPanelPedidosLayout);
        jPanelPedidosLayout.setHorizontalGroup(
            jPanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPedidosLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarPedidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExportarRepoPedidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImprimirRepoPedidos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelPedidosLayout.setVerticalGroup(
            jPanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPedidosLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtIDPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPedidos)
                    .addComponent(btnExportarRepoPedidos)
                    .addComponent(btnImprimirRepoPedidos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pedidos", jPanelPedidos);

        tablaRepoRegEntregas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tablaRepoRegEntregas);

        btnImprimirRepoRegEntregas.setText("Imprimir");

        btnExportarRepoRegEntregas.setText("Exportar");

        btnBuscarRegEntregas.setText("Buscar");

        jLabel8.setText("ID (Pedidos): ");

        javax.swing.GroupLayout jPanelRegEntregasLayout = new javax.swing.GroupLayout(jPanelRegEntregas);
        jPanelRegEntregas.setLayout(jPanelRegEntregasLayout);
        jPanelRegEntregasLayout.setHorizontalGroup(
            jPanelRegEntregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegEntregasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRegEntregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegEntregasLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDRegEntregas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarRegEntregas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExportarRepoRegEntregas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImprimirRepoRegEntregas)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelRegEntregasLayout.setVerticalGroup(
            jPanelRegEntregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegEntregasLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanelRegEntregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtIDRegEntregas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarRegEntregas)
                    .addComponent(btnExportarRepoRegEntregas)
                    .addComponent(btnImprimirRepoRegEntregas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reg. Entregas", jPanelRegEntregas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarGuiaRem;
    private javax.swing.JButton btnBuscarIDPedidosComandas;
    private javax.swing.JButton btnBuscarPedidos;
    private javax.swing.JButton btnBuscarRegEntregas;
    private javax.swing.JButton btnBuscarRepoBoletas;
    private javax.swing.JButton btnBuscarReportesClientes;
    private javax.swing.JButton btnExportarRepoBoletas;
    private javax.swing.JButton btnExportarRepoClientes;
    private javax.swing.JButton btnExportarRepoGuiaRem;
    private javax.swing.JButton btnExportarRepoPedidos;
    private javax.swing.JButton btnExportarRepoRegEntregas;
    private javax.swing.JButton btnExportarReportesComandas;
    private javax.swing.JButton btnImprimirGuiaRem;
    private javax.swing.JButton btnImprimirRepoComandas;
    private javax.swing.JButton btnImprimirRepoPedidos;
    private javax.swing.JButton btnImprimirRepoRegEntregas;
    private javax.swing.JButton btnImprimirReporteBoletas;
    private javax.swing.JButton btnRepoImprimir;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanelBoletas;
    private javax.swing.JPanel jPanelClientes;
    private javax.swing.JPanel jPanelComandas;
    private javax.swing.JPanel jPanelGuiaRem;
    private javax.swing.JPanel jPanelPedidos;
    private javax.swing.JPanel jPanelRegEntregas;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaRepoPedidos;
    private javax.swing.JTable tablaRepoRegEntregas;
    private javax.swing.JTable tablaReporteClientes;
    private javax.swing.JTable tablaReporteComandas;
    private javax.swing.JTable tablaReporteGuiaRem;
    private javax.swing.JTable tablaReportesBoletas;
    private javax.swing.JTextField txtClientesID;
    private javax.swing.JTextField txtIDBoletaBusqueda;
    private javax.swing.JTextField txtIDPedidoComandas;
    private javax.swing.JTextField txtIDPedidos;
    private javax.swing.JTextField txtIDPedidosGuiaRem;
    private javax.swing.JTextField txtIDRegEntregas;
    // End of variables declaration//GEN-END:variables
}
