/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorSistemaCocina;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author PC
 */
public class SistemaCocina extends javax.swing.JFrame {

    private panelCocinaPrincipal panelCocinaPrincipal;
    private detalleComanda detalleComanda;
    private CardLayout cardLayout;

    /**
     * Creates new form SistemaCocina
     */
    public SistemaCocina() {
        initComponents();

        // Inicialización de paneles y layout
        cardLayout = new CardLayout();
        PanelCambio.setLayout(cardLayout);

        panelCocinaPrincipal = new panelCocinaPrincipal();
        detalleComanda = new detalleComanda();

        PanelCambio.add(panelCocinaPrincipal, "panelCocinaPrincipal");
        PanelCambio.add(detalleComanda, "detalleComanda");

        cardLayout.show(PanelCambio, "panelCocinaPrincipal");
    }

    public void cambiarPanel(String nombre) {
        cardLayout.show(PanelCambio, nombre);
    }

    public panelCocinaPrincipal getPanelCocinaPrincipal() {
        return panelCocinaPrincipal;
    }

    public detalleComanda getDetalleComanda() {
        return detalleComanda;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCambio = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(720, 640));
        setMinimumSize(new java.awt.Dimension(720, 640));
        setPreferredSize(new java.awt.Dimension(720, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelCambio.setPreferredSize(new java.awt.Dimension(720, 640));

        javax.swing.GroupLayout PanelCambioLayout = new javax.swing.GroupLayout(PanelCambio);
        PanelCambio.setLayout(PanelCambioLayout);
        PanelCambioLayout.setHorizontalGroup(
            PanelCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        PanelCambioLayout.setVerticalGroup(
            PanelCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        getContentPane().add(PanelCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            SistemaCocina vista = new SistemaCocina();
            new ControladorSistemaCocina(vista);
            vista.setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCambio;
    // End of variables declaration//GEN-END:variables
}
