/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorEntrega;
import java.awt.CardLayout;

/**
 *
 * @author PC
 */
public class entregaVista extends javax.swing.JFrame {

    /**
     * Creates new form entregaVista
     */
    private EntregaPanel entregaPanel;
    private DetalleEntrega detalleEntrega;

    public entregaVista() {
        initComponents();

        // Inicializar paneles
        entregaPanel = new EntregaPanel();
        detalleEntrega = new DetalleEntrega();

        // Establecer layout
        jPanelCambio.setLayout(new CardLayout());

        // Agregar paneles al contenedor
        jPanelCambio.add(entregaPanel, "entregaPanel");
        jPanelCambio.add(detalleEntrega, "detalleEntrega");

        // Mostrar el panel principal
        cambiarPanel("entregaPanel");
    }

    public void cambiarPanel(String nombre) {
        ((CardLayout) jPanelCambio.getLayout()).show(jPanelCambio, nombre);
    }

    public EntregaPanel getEntregaPanel() {
        return entregaPanel;
    }

    public DetalleEntrega getDetalleEntrega() {
        return detalleEntrega;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCambio = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanelCambioLayout = new javax.swing.GroupLayout(jPanelCambio);
        jPanelCambio.setLayout(jPanelCambioLayout);
        jPanelCambioLayout.setHorizontalGroup(
            jPanelCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );
        jPanelCambioLayout.setVerticalGroup(
            jPanelCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Punto de entrada con el controlador
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            entregaVista vista = new entregaVista();
            new ControladorEntrega(vista); // Aquí conectamos todo
            vista.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelCambio;
    // End of variables declaration//GEN-END:variables
}
